from typing import TypedDict,List,Literal,get_args,NotRequired
from enum import Enum
from langchain_core.messages.base import BaseMessage
from langmem.short_term import RunningSummary
from langgraph.prebuilt.chat_agent_executor import AgentState


from pydantic import BaseModel, Field





class StepModal(BaseModel):
    """Represents a single execution step with breakdown and tool calls."""
    step_uid: str = Field(..., description="Unique identifier for this step")
    agent_name: str = Field(..., description="Name of the agent executing this step")
    instruction: str = Field(..., description="What the agent needs to do in this step")
    sub_steps: List[str] = Field(..., description="Sub-steps to be executed within this step")
    available_tools: List[str] = Field(..., description="Available tools from the agent")
    response_from_previous_step: List[str] = Field(..., description="optionally refer the previous responses by step_ids if its required")
    response: BaseMessage = Field(..., description="The response generated by the agent for this step")
    status: Literal["pending", "completed", "failed"]

class PlanOutputModal(BaseModel):
    """Schema for agent plan containing execution steps."""
    plan: List[StepModal] = Field(..., description="List of execution steps")


class CompletedStep:
    step_uid: str
    instruction: str
    response: BaseMessage

class ChatState(AgentState):
    messages: List[BaseMessage]
    tool_call_count: int
    thread_id: str 
    messages_history: List[BaseMessage]
    plan_executed: NotRequired[bool]
    plan: PlanOutputModal



class SupervisorNode:
    START_CONV = Literal["start_conv"]
    END_CONV = Literal["end_conv"]
    TOOLS = Literal["tools"]
    LLM = Literal["llm"]
    ROUTE = Literal["route"]
    SUPERVISOR = Literal["supervisor"]
    PLAN_EXECUTER = Literal["plan_executer"]
    CODING_AGENT = Literal["coding_agent"]
    RESEARCH_AGENT = Literal["research_agent"]
    STRUCTURED_OUTPUT_AGENT = Literal["structured_output_agent"]
    POST_AGENT_EXECUTION = Literal["post_agent_execution"]

    START_CONV_VAL = "start_conv"
    END_CONV_VAL = "end_conv"
    TOOLS_VAL = "tools"
    LLM_VAL = "llm"
    ROUTE_VAL = "route"
    SUPERVISOR_VAL = "supervisor"
    PLAN_EXECUTER_VAL = "plan_executer"
    CODING_AGENT_VAL = "coding_agent"
    RESEARCH_AGENT_VAL = "research_agent"
    STRUCTURED_OUTPUT_AGENT_VAL = "structured_output_agent"
    POST_AGENT_EXECUTION_VAL = "post_agent_execution"